apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels: {{- include "mosquitto.labels" . | nindent 4 }}
{{- with .Values.service.annotations }}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.ports.mqtt.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.ports.websocket.port }}
      protocol: TCP
      name: http-ws
  selector: {{- include "mosquitto.selector" . | nindent 4 }}
